### ISSUE TITLE
[DynamicData] Please create an SVG logo for this workbench

### ISSUE THREAD

**Issue by luzpaz** [mwganson/DynamicData#16]
For the new and improved Addon Manager https://github.com/FreeCAD/FreeCAD-addons/issues/37

**Comment by mwganson** [comment]
https://github.com/mwganson/DynamicData/blob/master/Resources/icons/DynamicDataSVGLogo.svg

**Comment by luzpaz** [comment]
:+1: 
https://github.com/FreeCAD/FreeCAD/pull/2297
