### ISSUE TITLE
Created Container can't be removed with Undo/Redo commands

### ISSUE THREAD

**Issue by ryanthara** [mwganson/DynamicData#56]
I take a look to your workbench and start realizing the power of the idea behind it.

When adding a dynamic data object into an empty document it can't be undone.

It is no problem to undo/redo the property changes, but the object creation can not be undone.

**Comment by mwganson** [comment]
I see in the source code commented out code to make object creation something you can undo.  I don't know why I would have commented it out.  I guess because dynamic properties were not supported at the time for all object types.  I will add this back in for the next version.
